name: CI for DatingApp-MainApi

on:
  push:
    branches:
      - master
      - production
  pull_request:
    branches:
      - production

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests and collect coverage
        run: npm run test

      - name: Enforce minimum coverage for production
        if: github.ref == 'refs/heads/production'
        run: npx nyc check-coverage --branches 70 --functions 70 --lines 70 --statements 70

      # - name: Lint the code
      #   run: npx eslint . 
      
